pyauth/python-pkcs11

README.rst
extern/pkcs11.h
extern/pkcs11f.h
extern/pkcs11t.h
pkcs11/defaults.py
pkcs11/mechanisms.py
tests/__init__.py
tests/test_aes.py

Updates the mechanism list with the new AES mechanisms.
Uses the new value for `AES_KEY_WRAP`. Sets `AES_KEY_WRAP` to the default AES keywrapping implementation.

PKCS#11 2016

---

pkcs11/_mswin.pxd
pkcs11/_pkcs11.pyx

Hi @danni,
Please find hereby a PR to fix issue #41. In addition, `winerror()` returns now a string now, which should ease troubleshooting. 
This PR passes local testing as well as travis build. (but admittedly, there is room for adding unit testing & matrix build for Windows).
For your review.
Eric

fixing #41 issue in exception handling and returning error string on Windows errors

---

pkcs11/_pkcs11.pyx
pkcs11/constants.py

Addresses #44.
Option to control the set of flags included in the template sent with C_UnwrapKey: flags that are False are removed.
Needed for some HSMs that don't accept all the flags even if they are set to False.

Issue #44: Option to remove False flags from the C_UnwrapKey template.

---

.travis.yml
extern/pkcs11t.h
pkcs11/defaults.py
pkcs11/mechanisms.py
pkcs11/util/ec.py
tests/test_ecc.py

I am interested in Ed25519 for inclusion in a Cryptoki interface to [our FIDO2 dongle](https://github.com/solokeys/solo). This curve is included in the [draft for Cryptoki v3.0](https://www.oasis-open.org/committees/document.php?document_id=62198&wg_abbrev=pkcs11), and implemented in [SoftHSMv2 version 2.5](https://github.com/opendnssec/SoftHSMv2/pull/362).
The OID patch would be removed if https://github.com/wbond/asn1crypto/pull/134 gets merged.
Submitting now for feedback. An automated test against SoftHSMv2 would be nice I guess :)
I ran the following against SoftHSM 2.5 successfully:
```
ed_params = session.create_domain_parameters(
p11.KeyType.EC_EDWARDS,
{
p11.Attribute.EC_PARAMS: encode_named_curve_parameters("Ed25519")
},
local=True,
)
ed_pub, ed_priv = …
```

RFC 8410 (Ed25519 and friends)

---

pkcs11/constants.py
pkcs11/defaults.py

This defines the COPYABLE attribute in the int enum.
CKA_COPYABLE is 0x171
Source: http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html
Reviewers @danni

Attribute.COPYABLE

---

pkcs11/defaults.py

Data objects may have this additional RFC2279 string to identify the application an object belongs to.
See http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959708 for the spec
I tested this change using a token that I created an object on using pkcs11-tool like this:
`pkcs11-tool --slot 0x2 --login --pin x --write-object ./testdata --type data --application-label app1 --label data1`

Allow unpacking Attribute.APPLICATION for data objects

---

pkcs11/_pkcs11.pyx

I was getting TokenNotPresent Exceptions when using lib.get_tokens(token_label="...") with multiple card readers, where the first slot didn't have a card in it. I think this try block was meant to be around the slot.get_token call all along.

Fix empty slot error handling in _pkcs11.lib.get_tokens

---

pkcs11/_pkcs11.pyx
pkcs11/_utils.pyx
tests/test_aes.py

This fixes #63. For string fields in Slot, Token and lib, string slices are now used instead of `_fix_string_label`.

Changed _fix_string_length calls to instead use string slices.

---

pkcs11/_pkcs11.pyx

Initialize ulValueLen to zero in __getitem__

---

pkcs11/_pkcs11.pyx
pkcs11/types.py

Some pkcs11 libs offer a 'protected authentication' path (CKF_PROTECTED_AUTHENTICATION_PATH) e.g. keychain-pkcs11, HID ActivClient support this feature (OpenSC does not). 
This is a useful feature so that application devs do not have to collect/manage/zero pin credentials themselves.
It seems to make sense to add an additional boolean to the open function for developers who know they are using a library that supports protected authentication.

pkcs11/_pkcs11.pyx: add support for protected authentication

---

pkcs11/_errors.pyx
pkcs11/_pkcs11.pyx
pkcs11/_pkcs11_defn.pxd

Release the Python global interpreter lock while making calls to the
PKCS#11 C_Sign and C_SignFinal functions, to allow other Python threads
to run while a sign operation is in progress. This is helpful when the
sign call blocks waiting for user interaction, such as the user needing
to touch a security key.

Change SignMixin to release GIL when calling C_Sign/C_SignFinal

---

README.rst

Closes issue https://github.com/danni/python-pkcs11/issues/54

Change ECDSA example to use the original "secp256r1" curve name

---

docs/api.rst
pkcs11/_errors.pyx
pkcs11/_pkcs11.pyx
pkcs11/_pkcs11_defn.pxd
pkcs11/exceptions.py

Add wait for slot event functionality to the lib class. Useful for detecting if a token was removed/added. 
I went back and forth on how to represent the CKR_NO_EVENT response from the api and whether it should be an int or raise an exception (even though it's not really an error).

pkcs11/_pkcs11.pyx: add wait_for_slot_event

---

dev-requirements.in
dev-requirements.txt
pkcs11/_pkcs11.pyx
pkcs11/_pkcs11_defn.pxd
tests/test_aes.py

Additional Information:
1. Added AES Key Derivation mechanisms described in
PKCS11 v2.4.0 Section 2.15:
- CKM_AES_ECB_ENCRYPT_DATA
- CKM_AES_CBC_ENCRYPT_DATA
Sanity Testing:
1. Build Validation:
python setup.py build_ext --inplace
2. AES Testing:
export PKCS11_MODULE=XXX
export PKCS11_TOKEN_LABEL=XXX
export PKCS11_TOKEN_PIN=XXX
export PKCS11_TOKEN_SO_PIN=XXX
pytest ./tests/test_aes.py
Signed-off-by: Akshitij Malik

Add AES Key Derivation Support (ECB,CBC Encrypt)

---

pkcs11/_pkcs11.pyx

From PKCS#11 perspective, the CKM_ECDH1_DERIVE and CKM_ECDH1_COFACTOR_DERIVE has a same API (mechanism parameters).
This is a simple extension that allows to do CKM_ECDH1_COFACTOR_DERIVE in python-pkcs11.
Tested on Utimaco CryptoServer CP5 HSM card.

Extends the ECDH to cofactor variant

---

pkcs11/_pkcs11.pyx
pkcs11/types.py

For private key objects with the CKA_ALWAYS_AUTHENTICATE attribute set, accept an optional pin.  If provided, calls C_Login after SignInit() or DecryptInit().
Resolves #72 
Tested on YubiKey 4.

Add optional pin argument for sign and decrypt

---

pkcs11/_pkcs11.pyx
pkcs11/types.py

Thales in Luna HSM 7 SDKs  is using vendor-defined CK_USER_TYPEs. Specifically, Thales is using 0x80000001, 0x80000002, 0x80000003 to allow for some role separation in use of keys in the HSM.
This commit allows specifying the user type as an alternative to the default 0x1(CKU_USER).
```
// extracted from Thales Luna HSM 7 C header files
#define CKU_LIMITED_USER            0x80000001
#define CKU_AUDIT                   0x80000002
#define CKU_LIMITED_CRYPTO_OFFICER  0x80000003
```

Allow vendor defined CK_USER_TYPE in C_Login

---

setup.py

Fixes #133 and provides support for automatic installation using "pip install python-pkcs11" in Python 3.10. 
Tested on Windows 11, multiple conda virtual env.

Fix #133 and support Python 3.10

---

pkcs11/_pkcs11.pyx

Changed typo on L380 from `CK_OBJECT_HANDLE` to `CK_SESSION_HANDLE`.
Resolves #147

Fix typo in _pkcs11.pyx

---

docs/opensc.rst
tests/test_public_key_external.py

Also update docs to match
Fixes:
```
CryptographyDeprecationWarning: Curve argument must be an instance of an EllipticCurve class.
```

fix DeprecationWarning in test_ecdh

---

pkcs11/__init__.py

Currently, you cant  actually import any of the utils, since they arent brought up to the head __init__.

add util imports so examples are usable

---

pkcs11/constants.py

PROFILE ObjectClass was missing as one of object classes found in OpenSC

Added PROFILE ObjectClass

---

tests/test_dh.py

Fixes:
```
BotanDH.cpp(264): Failed to generate 512 bit DH parameters: DL_Group: prime size 512 is too small
```
Neeed for botan 1.11.22 and later

test_generate_params: use size 1024

---

pkcs11/_pkcs11.pyx
pkcs11/defaults.py

This commit provides a fix for issue #140.
- Adding a default mechanism for `CKK_GENERIC_SECRET` key type
- Fixing condition for including `CKA_VALUE_LEN` when generating a secret key. It is now skipped only for those algorithms that do not want it.

fix for issue #140 : lack of support for generation of CKK_GENERIC_SECRET key type

---

extern/load_module.c
tests/test_slots_and_tokens.py

I've been doing some experiments to try and remove the limitation that prevents multiple PKCS#11 modules from being loaded at once, and I noticed an unfortunate regression in the library loading handler on POSIX systems. #202 introduced an incorrect call to `PyMem_Free()` in there.
I've fixed it, added a test, and also added some more safeguards against error message decoding issues. We might have push out a bugfix release to address this, though, since it'll in particular cause segfaults when trying to load nonexistent libs.
Sorry about that :/

Fix p11_error() implementation and test it

---

pkcs11/_pkcs11.pyx
tests/test_sessions.py

This is a 2nd attempt, because the last rebase in my previous pull request (https://github.com/pyauth/python-pkcs11/pull/200) broke the logic and I missed it. This corrects that oversight.
The PKCS#11 specification states
```
The constant CK_UNAVAILABLE_INFORMATION is used in the ulValueLen field to denote an invalid or unavailable value. See C_GetAttributeValue for further details.
```
This MR exposes the `CK_UNAVAILABLE_INFORMATION` constant definition (along with `CK_EFFECTIVELY_INFINITE` which is defined next to it, for completeness sake) and checks for that result after calling `C_GetAttributeValue`
This corrects a crash when a PKCS#11 module returns this. I believe this will fix the following issues:
https://github.com/pyauth/python-pkcs11/issues/139 …

Correctly handle CK_UNAVAILABLE_INFORMATION (2nd attempt)

---

.github/actions/install-opencryptoki/action.yml
.github/workflows/tests.yml
tests/test_sessions.py
tests/test_slots_and_tokens.py

In test runs on Linux, run tests against both opencryptoki and SoftHSM.
This uses opencryptoki's software token.

Enable opencryptoki in CI

---

pkcs11/types.py

As previously discussed in https://github.com/pyauth/python-pkcs11/pull/214
This PR makes _CK_UTF8CHAR_to_str more robust against non-compliant tokens.

Use "replace" error strategy for utf-8 decoding

---

pkcs11/_pkcs11.pyx
pkcs11/types.py
tests/test_sessions.py

This PR is an adaption of https://github.com/pyauth/python-pkcs11/pull/161

Add PIN management functionality
